terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
  }
}

############################
# GitHub Provider (App Auth)
############################
provider "github" {
  owner = var.github_org

  app_auth {
    id              = var.app_id
    installation_id = var.app_installation_id
    pem_file        = file("private-key.pem")
  }
}

############################
# Get main branch SHA
############################
data "github_branch" "main" {
  repository = var.repository
  branch     = "main"
}

############################
# Create feature branch
############################
resource "github_branch" "ads_branch" {
  repository = var.repository
  branch     = "feature/add-ads-config"
  source_sha = data.github_branch.main.sha
}

############################
# Create ADS JSON file
############################
resource "github_repository_file" "ads_definition" {
  repository = var.repository
  branch     = github_branch.ads_branch.branch
  file       = "ads/attach-data-source.json"

  content = jsonencode({
    ruleType = "AttachDataSource"
    state = {
      dev = "active"
    }
    team          = "StrawHats"
    operatingTeam = "StrawHats"
    metadata      = {}
    dataAccess = {
      dev = {
        "sakthikavin.ss@thoughtworks.com" = "user"
      }
    }
    localTokenizationPolicy = {}
    sourceAdapter = {
      adapterType = "Kafka"
      parameters  = {}
    }
  })

  commit_message      = "Add AttachDataSource ADS configuration"
  commit_author       = "Terraform Automation"
  commit_email        = "automation@company.com"
  overwrite_on_create = true
}

###################################
# Create dummy GitHub Actions flow
###################################
resource "github_repository_file" "dummy_workflow" {
  repository = var.repository
  branch     = github_branch.ads_branch.branch
  file       = ".github/workflows/dummy.yml"

  content = <<-EOT
    name: Dummy Workflow

    on:
      pull_request:
        branches: [ main ]
      push:
        branches: [ main ]

    jobs:
      dummy-job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Print message
            run: echo "This is a dummy GitHub Action created by Terraform"
  EOT

  commit_message      = "Add dummy GitHub Actions workflow"
  commit_author       = "Terraform Automation"
  commit_email        = "automation@example.com"
  overwrite_on_create = true
}

############################
# Create Pull Request
############################
resource "github_repository_pull_request" "ads_pr" {
  base_repository = var.repository
  title           = "Add AttachDataSource ADS configuration"

  body = <<-EOT
    ## New ADS Configuration

    **Rule Type:** AttachDataSource  
    **Team:** StrawHats  
    **Source Adapter:** Kafka  

    ---
    Auto generated by Terraform
  EOT

  base_ref = "main"
  head_ref = github_branch.ads_branch.branch

  depends_on = [
    github_repository_file.ads_definition,
    github_repository_file.dummy_workflow
  ]
}

############################
# Outputs
############################
output "pull_request_url" {
  value = "https://github.com/${var.github_org}/${var.repository}/pull/${github_repository_pull_request.ads_pr.number}"
}
